### ISSUE TITLE
getTCGA() error

### ISSUE THREAD

**Issue by MohamedRefaat92** [Jfortin1/tcgaR#2]
Hello
I tried getTCGA() from the help file of the function and I got this:

> obj <- getTCGA("coad", datatype="methylation", platform="27k", n.samples=10)
Error in .getTCGA.meth(cancer = cancer, platform = platform, verbose = verbose, : The cancer type is not available for this platform

Can anyone help me?
Thanks in advance.

**Comment by Jfortin1** [comment]
Sadly the old TCGA portal has been replaced, and this package is now deprecated
